export const CHANGE_INPUT_VALUE = "CHANGE_CHILD_DIVISION_INPUT_VALUE";
export const EMPTY_CHILD_DIVISION_INPUT = "EMPTY_CHILD_DIVISION_INPUT";
export const CREATE_CHILD_DIVISION = "CREATE_CHILD_DIVISION";
export const UPDATE_CHILD_DIVISION = "UPDATE_CHILD_DIVISION";
export const GET_CHILD_DIVISION_LIST = "GET_CHILD_DIVISION_LIST";
export const GET_CHILD_DIVISION_DETAILS = "GET_CHILD_DIVISION_DETAILS";
export const DELETE_CHILD_DIVISION = "DELETE_CHILD_DIVISION";
export const GET_CHILD_DIVISION_DROPDOWN = "GET_CHILD_DIVISION_DROPDOWN";