export const CHANGE_INPUT_VALUE = "CHANGE_DEPARTMENT_INPUT_VALUE";
export const EMPTY_DEPARTMENT_INPUT = "EMPTY_DEPARTMENT_INPUT";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const GET_DEPARTMENT_DETAILS = "GET_DEPARTMENT_DETAILS";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const GET_DEPARTMENT_DROPDOWN = "GET_DEPARTMENT_DROPDOWN";