export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const EMPTY_DESIGNATION_INPUT = "EMPTY_DESIGNATION_INPUT";
export const SUBMIT_DESIGNATION = "SUBMIT_DESIGNATION";
export const GET_DESIGNATION_DETAILS = "GET_DESIGNATION_DETAILS";
export const DELETE_DESIGNATION = "DELETE_DESIGNATION";
export const GET_DESIGNATION_LIST = "GET_DESIGNATION_LIST";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";
export const GET_DESIGNATION_DROPDOWN = "GET_DESIGNATION_DROPDOWN";