export const CHANGE_INPUT_VALUE = "CHANGE_DIVISION_INPUT_VALUE";
export const EMPTY_DIVISION_INPUT = "EMPTY_DIVISION_INPUT";
export const CREATE_DIVISION = "CREATE_DIVISION";
export const UPDATE_DIVISION = "UPDATE_DIVISION";
export const GET_DIVISION_LIST = "GET_DIVISION_LIST";
export const GET_DIVISION_DETAILS = "GET_DIVISION_DETAILS";
export const DELETE_DIVISION = "DELETE_DIVISION";
export const GET_DIVISION_DROPDOWN = "GET_DIVISION_DROPDOWN";