export const CHANGE_INPUT_VALUE = "CHANGE_OCCUPATION_INPUT_VALUE";
export const EMPTY_OCCUPATION_INPUT = "EMPTY_OCCUPATION_INPUT";
export const SUBMIT_OCCUPATION = "SUBMIT_OCCUPATION";
export const GET_OCCUPATION_LIST = "GET_OCCUPATION_LIST";
export const GET_OCCUPATION_DETAILS = "GET_OCCUPATION_DETAILS";
export const DELETE_OCCUPATION = "DELETE_OCCUPATION";
export const UPDATE_OCCUPATION = "UPDATE_OCCUPATION";
export const GET_OCCUPATION_DROPDOWN = "GET_OCCUPATION_DROPDOWN";

export const GET_OCCUPATION_LIST_BY_SEARCH = "GET_OCCUPATION_LIST_BY_SEARCH";
export const GET_OCCUPATION_DROPDOWN_LIST = "GET_OCCUPATION_DROPDOWN_LIST";
