export const CHANGE_INPUT_VALUE = "CHANGE_SUB_DIVISION_INPUT_VALUE";
export const EMPTY_SUB_DIVISION_INPUT = "EMPTY_SUB_DIVISION_INPUT";
export const CREATE_SUB_DIVISION = "CREATE_SUB_DIVISION";
export const UPDATE_SUB_DIVISION = "UPDATE_SUB_DIVISION";
export const GET_SUB_DIVISION_LIST = "GET_SUB_DIVISION_LIST";
export const GET_SUB_DIVISION_DETAILS = "GET_SUB_DIVISION_DETAILS";
export const DELETE_SUB_DIVISION = "DELETE_SUB_DIVISION";
export const GET_SUB_DIVISION_DROPDOWN = "GET_SUB_DIVISION_DROPDOWN";